services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: balanceApp
    ports:
      - '3306:3306'
    volumes:
      - ./scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - default
    restart: on-failure
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
