services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: balanceApp
    ports:
      - '3306:3306'
    volumes:
      - ../scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
